#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2026-present, Bernd Fix >Y<
# SPDX-License-Identifier: AGPL-3.0-only

ASDK=/usr/lib/android-sdk/build-tools/34.0.0
KEYSTORE=/usr/local/src/keystore.jks
KEY=dev

#-----------------------------------------------------------------------

APK_R1=app/build/outputs/apk/arm64/release/app-arm64-release-unsigned.apk
APK_R2=app/build/outputs/apk/amd64/release/app-amd64-release-unsigned.apk

APK_D1=app/build/outputs/apk/arm64/debug/app-arm64-debug.apk
APK_D2=app/build/outputs/apk/amd64/debug/app-amd64-debug.apk

cd apk/
rm deploy/*.apk*
rm ${APK_R1} ${APK_D1} ${APK_R2} ${APK_D2}

echo "Building APKS..."
./gradlew clean build --no-daemon --no-build-cache
[ $? -ne 0 ] && exit 1

ls -l ${APK_R1} ${APK_D1} ${APK_R2} ${APK_D2}

echo "Signing APKS..."
if [ -e ${APK_R1} ]; then
    ${ASDK}/zipalign -v 4 ${APK_R1} deploy/kpclientd-arm64-v8a-release-aligned.apk > /dev/null 2>&1
    ${ASDK}/apksigner sign --ks ${KEYSTORE} --ks-key-alias ${KEY} --out deploy/kpclientd.arm64-v8a.apk deploy/kpclientd-arm64-v8a-release-aligned.apk
    ls -l deploy/kpclientd.arm64-v8a.apk
fi
if [ -e ${APK_R2} ]; then
    ${ASDK}/zipalign -v 4 ${APK_R2} deploy/kpclientd-x86_64-release-aligned.apk > /dev/null 2>&1
    ${ASDK}/apksigner sign --ks ${KEYSTORE} --ks-key-alias ${KEY} --out deploy/kpclientd.x86_64.apk deploy/kpclientd-x86_64-release-aligned.apk
    ls -l deploy/kpclientd.x86_64.apk
fi

exit 0
