#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2026-present, Bernd Fix >Y<
# SPDX-License-Identifier: AGPL-3.0-only

ASDK=/usr/lib/android-sdk/build-tools/34.0.0
KEYSTORE=/usr/local/src/keystore.jks
KEY=dev

#-----------------------------------------------------------------------

APK_R=app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
APK_D=app/build/outputs/apk/debug/app-arm64-v8a-debug.apk

cd apk/
rm deploy/*.apk*
rm ${APK_R} ${APK_D}

./gradlew clean build --no-daemon --no-build-cache
[ $? -ne 0 ] && exit 1

[ ! -e ${APK_R} ] && exit 1

${ASDK}/zipalign -v 4 ${APK_R} deploy/kpclientd-release-aligned.apk > /dev/null 2>&1
${ASDK}/apksigner sign --ks ${KEYSTORE} --ks-key-alias ${KEY} --out deploy/kpclientd.apk deploy/kpclientd-release-aligned.apk

if [ "$1" = "+deploy" ]; then
    adb push deploy/kpclientd.apk /sdcard/Download
    adb push ${APK_D} /sdcard/Download/kpclientd-debug.apk
fi
exit 0
