plugins {
    id 'com.android.application'
}

android {
    namespace 'org.hoi_polloi.kpdaemon'
    compileSdk 36

    defaultConfig {
        applicationId "org.hoi_polloi.kpdaemon"
        minSdk 33
        targetSdk 36
        versionCode 1000000
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    splits {
        abi {
            enable true
            reset()
            include "arm64-v8a"
            universalApk false
        }
    }

    buildTypes {
        release {
            optimization {
                enable(false)
            }
            minifyEnabled false
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17

        tasks.withType(JavaCompile).configureEach {
            options.compilerArgs << "-Xlint:deprecation"
        }
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    packaging {
        resources {
            excludes += 'META-INF/maven/io.opencensus/**'
            excludes += 'META-INF/io.opencensus/**'
            excludes += '**/io.opencensus/**/*.properties'
            excludes += '**/io.opencensus/**/*.class'
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.cardview
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}
